# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

Category.delete_all
Location.delete_all
Post.delete_all

Category.create({cateogry_name: "Food"})
Category.create({cateogry_name: "Bars"})
Category.create({cateogry_name: "Sights"})
Category.create({cateogry_name: "Outdoors"})
Category.create({cateogry_name: "Just for Fun"})
Category.create({cateogry_name: "Culture"})
Category.create({cateogry_name: "Shopping"})

Location.create({street_address: "24 Reed St", city: "Brooklyn", state: "NY", location_name: "Brooklyn Crab", location_notes: "Great Views", location_category_id: 1})
Location.create({street_address: "337 3rd Ave", city: "New York", state: "NY", location_name: "Rose Hill Tavern", location_notes: "Sports Bar", location_category_id: 2})
Location.create({street_address: "129 Macdougal St", city: "New York", state: "NY", location_name: "La Lanterna Di Vittorio", location_category_id: 1})
Location.create({city: "New York", state: "NY", cross_st1: "E 106th", cross_st2: "Park", location_name: "Graffiti Wall of Fame", location_notes: "Art", location_category_id: 6})
Location.create({street_address: "117 Macdougal St", city: "New York", state: "NY", location_name: "Olive Tree Cafe & Bar", location_notes: "Atmosphere", location_category_id: 1})
Location.create({street_address: "1220 5th Ave", city: "New York", state: "NY", location_name: "Museum of the City of New York", location_notes: "Limited Hours", location_category_id: 6})
Location.create({street_address: "459 Broome St", city: "New York", state: "NY", location_name: "Purl Soho", location_category_id: 7})
Location.create({street_address: "530 W 27th St", city: "New York", state: "NY", location_name: "Sleep No More", location_notes: "Theater, Experience", location_category_id: 6})
Location.create({street_address: "315 9th St", city: "New York", state: "NY", location_name: "Verameat", location_notes: "Jewelry", location_category_id: 7})
Location.create({street_address: "99 Margaret Corbin Dr", city: "New York", state: "NY", location_name: "The Cloisters", location_notes: "Art", location_category_id: 6})
Location.create({city: "New York", state: "NY", cross_st1: "Madison Ave", cross_st2: "E 23rd St", location_name: "Shake Shack", location_category_id: 1})
Location.create({street_address: "222 E 6th St", city: "New York", state: "NY", location_name: "Ukrainian Museum", location_notes: "History", location_category_id: 6})
Location.create({street_address: "248 Mercer St", city: "New York", state: "NY", location_name: "Think Coffee", location_notes: "Coffee", location_category_id: 1})
Location.create({street_address: "441 Clarke Ave", city: "Staten Island", state: "NY", location_name: "Historic Richmond Town", location_category_id: 3})
Location.create({street_address: "79 N 11th St", city: "Brooklyn", state: "NY", location_name: "Brooklyn Brewery", location_notes: "Tour", location_category_id: 5})
Location.create({street_address: "113 N 3rd St", city: "Brooklyn", state: "NY", location_name: "Radegast Hall", location_category_id: 2})
Location.create({street_address: "222 W 44th St", city: "New York", state: "NY", location_name: "Bowlmor", location_notes: "Bowling", location_category_id: 5})
Location.create({street_address: "882 3rd Ave", city: "Brooklyn", state: "NY", location_name: "Rooftop Films", location_category_id: 6})
Location.create({street_address: "10 South St", city: "New York", state: "NY", location_name: "Governor's Island", location_notes: "Address is for Ferry", location_category_id: 3})
Location.create({street_address: "700 E 9th St", city: "New York", state: "NY", location_name: "The Wayland", location_category_id: 5})
Location.create({street_address: "115 Macdougal St", city: "New York", state: "NY", location_name: "Cafe Wha?", location_notes: "Coffee" location_category_id: 1})
Location.create({street_address: "66 N 6th St", city: "New York", state: "NY", location_name: "Music Hall of Williamsburg",  location_category_id: 5})
Location.create({city: "New York", state: "NY", cross_st1: "34th St", cross_st2: "East River", location_name: "East River Ferry", location_notes: "Cheap", location_category_id: 4})
Location.create({street_address: "Liberty Island", city: "New York", state: "NY", location_name: "Statue of Liberty",  location_category_id: 3})
Location.create({city: "New York", state: "NY", cross_st1: "Central Park W", cross_st2: "86th St", location_name: "Central Park", location_notes: "Cheap", location_category_id: 4})
Location.create({street_address: "350 5th Ave", city: "New York", state: "NY", location_name: "Empire State Building",  location_category_id: 3})
Location.create({street_address: "1000 5th Ave", city: "New York", state: "NY", location_name: "Metropolitan Museum of Art",  location_category_id: 4})
Location.create({city: "New York", state: "NY", cross_st1: "W 46th St", cross_st2: "7th Ave", location_name: "Times Square", location_category_id: 3})
Location.create({street_address: "1071 5th Ave", city: "New York", state: "NY", location_name: "Guggenheim Museum",  location_category_id: 6})
Location.create({street_address: "45 Rockefeller Plaza", city: "New York", state: "NY", location_name: "Rockafeller Center",  location_category_id: 3})
Location.create({street_address: "Ellis Island", city: "New York", state: "NY", location_name: "Ellis Island",  location_category_id: 3})
Location.create({street_address: "231 E 14th St", city: "Brooklyn", state: "NY", location_name: "Beauty Bar", location_category_id: 2})
Location.create({street_address: "234 W 42nd St", city: "New York", state: "NY", location_name: "Madame Tussauds", location_notes: "Wax People", location_category_id: 3})
Location.create({street_address: "43-50 Main St", city: "Flushing", state: "NY", location_name: "Queens Bothanical Garden", location_category_id: 4})
Location.create({street_address: "180 Greenwich St.", city: "New York", state: "NY", location_name: "9/11 Memorial", location_notes: "Never Forget", location_category_id: 3})
Location.create({city: "New York", state: "NY", cross_st1: "Parkside Ave", cross_st2: "Coney Island Ave", location_name: "Prospect Park", location_category_id: 4})
Location.create({city: "New York", state: "NY", cross_st1: "Central Park W", cross_st2: "79th St", location_name: "American Museum of Natural History", location_category_id: 3})
Location.create({street_address: "500 E 9th St", city: "New York", state: "NY", location_name: "Tompkins Square Park", location_notes: "Fresh Air", location_category_id: 4})
Location.create({street_address: "2300 Southern Blvd", city: "Bronx", state: "NY", location_name: "Bronx Zoo", location_category_id: 3})
Location.create({city: "New York", state: "NY", cross_st1: "W 23rd St", cross_st2: "10th Ave", location_name: "High Line", location_category_id: 4})
Location.create({street_address: "1000 Surf Ave", city: "Broooklyn", state: "NY", location_name: "Luna Park - Coney Island", location_category_id: 3})
Location.create({city: "Flushing", state: "NY", cross_st1: "Rose Ave", cross_st2: "Oak Ave", location_name: "Kissena Park", location_category_id: 4})
Location.create({city: "New York", state: "NY", cross_st1: "W 46th St", cross_st2: "12th Ave", location_name: "Intrepid Sea Air and Space Museum", location_category_id: 3})
Location.create({street_address: "36-01 35th Ave", city: "Queens", state: "NY", location_name: "Museum of the Moving Image", location_category_id: 6})
Location.create({street_address: "422 Weaver Ave", city: "Bayside", state: "NY", location_name: "Fort Totten", location_category_id: 3})


Post.create({title:"Great Seafood at Brooklyn Crab", image:"http://brooklyn.happeningmag.com/wp-content/uploads/crab.jpg", content:"", vote_up:0, vote_down:0, user_id:1, location_id:1 , category_id:1})
Post.create({title:"Brooklyn Crab not for Girls", image:"http://www.gastrochic.com/t/wp-content/uploads/2014/08/brooklyn-crab-10.jpg", content:"the amount of bros in this establishment was just ridiculous. so ridiculous in fact, that i got the heebie jeebies and had to leave. i thought i was at the frying pan, but in red hook, brooklyn??? i then realized the water taxi drops you off around the corner, and that is 100% where these bros are coming from. murray hill 34th st. i am willing to give this place another try. the games did look fun and the rooftop umbrellas seem inviting. maybe not on a saturday afternoon...", vote_up:0 , vote_down:0 , user_id:1 , location_id:1 , category_id:1  })
Post.create({title:"Watch Sports at Rose Hill Tavern", image:"http://s3-media4.fl.yelpcdn.com/bphoto/NCNPJSJ77V4abst58wogGw/ls.jpg", content:"It's a medium sized rather cozy sports bar with lots of TVs that is mainly not crowded and much less impersonal that most other sports bars. You quickly get to know the bartenders and staff.", vote_up:0 , vote_down:0 , user_id:1 , location_id:2 , category_id:2  })
Post.create({title:"Don't Skip Dessert!", image:"http://foodnetwork.sndimg.com/content/dam/images/food/fullset/2011/2/4/2/RX-FNM_030111-Sugar-Fix-005_s4x3.jpg.rend.sni12col.landscape.jpeg", content:"It a great Italian cafe. Desserts and coffees are to die for. You can sit in the main area, in the enclosed garden or downstairs where they have a very cozy fireplace and live jazz in the evenings. Excellent for dates and intimate hangouts with friends.", vote_up:0 , vote_down:0 , user_id:1 , location_id:3 , category_id:1  })
Post.create({title:"Silent Movies Make Dinner a Delight", image:"https://lh3.googleusercontent.com/-zg34smSaX0Y/UVUfVzsZD6I/AAAAAAAAOcU/xMTH_UP_OyI/w120-h180-p-o/", content:"A great Israeli Mediterranean/Middle Eastern food place where Charlie Chaplin movies are being (silently - no honky-tonk soundtrack) projected on a screen. You are also provided with a cup of chalks so you can draw on your dining table. Occasionally they feature live music - last time I was there, it was a flamenco-style duet.", vote_up:0 , vote_down:0 , user_id:1 , location_id:4 , category_id:1  })
Post.create({title:"Street Art is Still Art", image:"http://wp.nyu.edu/harlem/wp-content/uploads/sites/726/2014/11/graffiti-hall-of-fame.jpg", content:"The art is always in flux, so worth a re-visit. For more than 30 years local artist have been showing off their skills on the giant wall next to the Metro North tracks. The park isn't always open so it can be difficult to get close, but it still looks awesome through a fence.", vote_up:0 , vote_down:0 , user_id:1 , location_id:5 , category_id:6  })
Post.create({title:"Learn About The Big Apple", image:"http://www.google.com/imgres?imgurl=https://s3.amazonaws.com/webassets.ticketmob.com/TM/images/PresentedBy/00AF8A90-AB31-795E-A4F7E23ACF99A18D.jpg&imgrefurl=http://nyadventureclub.ticketmob.com/event.cfm?id%3D53423&h=400&w=600&tbnid=COW-UmItp2Fy-M:&zoom=1&docid=4KSpn09vPNE7hM&ei=RjykVdeLEIOHwQSX9Jv4Cw&tbm=isch&ved=0CBwQMygAMABqFQoTCNfG3MWU2cYCFYNDkAodF_oGvw", content:"After a visit to the museum even lifetime New Yorkers have learned something. The permanent collection is impressive and the temporary shows are often fascinating.", vote_up:0 , vote_down:0 , user_id:1 , location_id:6 , category_id:6  })
Post.create({title:"Instragram Comes to Life in this Bright Store", image:"https://mmonroedesigninspiration.files.wordpress.com/2010/07/purl-yarn.jpg", content:"Purl Soho looks like it came straight out of an Instagram page. There are shelves upon shelves of yarn, ribbon and cloth to delight the eye. They're always ready with advice and good projects so even if you don't know where to start you will once it's over.", vote_up:0 , vote_down:0 , user_id:1 , location_id:7 , category_id:7  })
Post.create({title:"Sleep No More Brings You Right Up To Macbeth", image:"http://edwarderice.com/wp-content/uploads/2013/03/sleep-no-more-plays-six-nights-a-week-with-five-different-start-times-and-will-run-you-about-95-on-friday-and-saturday-nights-there-are-five-additional-late-night-times-and-you-can-stay-inside-the-hotel-for-up-to-three-hours.jpg", content:"Prepare for theater like you've never seen it before. Sleep no more is based off of Macbeth, but has the audience don white masks and walk the 5 story abandoned warehouse. It's like a freely moving bizarre dream. It's hard to say much more without ruining the surprise, but it's worthwhile!", vote_up:0 , vote_down:0 , user_id:1 , location_id:8 , category_id:6  })
Post.create({title:"Amazing Italian!", image:"http://wavenuelife.com/wp-content/uploads/2014/10/16684.jpg", content:"I love going downstairs and hanging out with friends. It's where I bring any woman I'm dating, it makes me see chic and romantic", vote_up:0 , vote_down:0 , user_id:1 , location_id:3 , category_id:1  })
Post.create({title:"The Met Part 2", image:"http://www.metmuseum.org/~/media/Images/Visit/The%20Cloisters/Cloisters_Accessibility.jpg?h=330&mw=495&w=495", content:"It's included in your admission to the Met, but it might be worth taking a day for it on its own. This is where they display their medieval art and architecture. It also has stunning views, stained glass windows, and immaculate courtyards. I recommend walking there from the subway stop, but there is a bus if you don't like to walk.", vote_up:0 , vote_down:0 , user_id:1 , location_id:9 , category_id:6  })
Post.create({title:"The Cloisters are Amazing", image:"http://blog.vaulttravel.com/wp-content/uploads/2015/05/the_cloisters_3.jpg", content:"Just the view alone is worthwhile. Better, it's pay what you can so you can manage it on any budget.", vote_up:0 , vote_down:0 , user_id:1 , location_id:9 , category_id:6  })
Post.create({title:"Step Back in Time", image:"http://www.metmuseum.org/~/media/Images/Visit/The%20Cloisters/Cloisters_Accessibility.jpg?h=330&mw=495&w=495", content:"Walking through the cloisters is the closest you can get to a time machine. I've always wanted to wear a long gown and make my husband wear hose before we go there.", vote_up:0 , vote_down:0 , user_id:1 , location_id:9 , category_id:6  })
Post.create({title:"An echo from the past that you can reach by bus", image:"http://www.metmuseum.org/~/media/Images/Visit/The%20Cloisters/Cloisters_Accessibility.jpg?h=330&mw=495&w=495", content:"If you're a museum person, the cloisters are a must see. I mean, how could you pass up a chance to see such beauty?", vote_up:0 , vote_down:0 , user_id:9 , location_id:6 , category_id:6  })
Post.create({title:"Better then the Met", image:"http://dguides.com/images/newyorkcity/attractions/the-cloisters.jpg", content:"I adore this place. It was my favorite when I spent a year in NYC getting my MBA and it's my favorite still. If you luck out, they sometimes have live performances of Gregorian Chants or acapella groups", vote_up:0 , vote_down:0 , user_id:1 , location_id:9 , category_id:6  })
Post.create({title:"The Cloisters", image:"http://dguides.com/images/newyorkcity/attractions/the-cloisters.jpg", content:"Simply gorgious. I think everyone should go here at least once in their lives", vote_up:0 , vote_down:0 , user_id:1 , location_id:9 , category_id:6  })
Post.create({title:"Ukrainian Pride!", image:"http://fl-tek.com/jbugajski/wp-content/uploads/2013/03/Large-size-Ukrainian-flag-wallpaper.jpg", content:"There's been a strong Ukrainian presence in the East Village and this museum celebrates it. The staff is passionate about preserving the culture. It is often missed, but worth the trip. You can learn a lot there and, with Ukraine in the news these days, it's even more important.", vote_up:0 , vote_down:0 , user_id:1 , location_id:10 , category_id:6  })
Post.create({title:"Be the envy of your friends with this bling", image:"https://encrypted-tbn3.gstatic.com/images?q=tbn:ANd9GcQDeMZm1H85dD5Bq1J5uGS5BMEaPYmHn4_J0iXtjQBD5VwqLymN9A", content:"It seems more like a studio from the outside, but this is THE place to go for quirky, and stylish jewelry. There's an accompanying clothing store a few blocks down.", vote_up:0 , vote_down:0 , user_id:1 , location_id:11 , category_id:7  })

